services:
  mysql-master:
    build:
      context: DB
      dockerfile: Dockerfile.master
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - master_data:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - mysql-net
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-replica:
    build:
      context: DB
      dockerfile: Dockerfile.replica
    container_name: mysql-replica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - replica_data:/var/lib/mysql
    ports:
      - "3311:3306"
    networks:
      - mysql-net
    depends_on:
      mysql-master:
        condition: service_healthy
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  fastapi:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: fastapi
    depends_on:
      mysql-master:
        condition: service_healthy  
      mysql-replica:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - mysql-net
    environment:
      - DB_MASTER_HOST=mysql-master
      - DB_REPLICA_HOST=mysql-replica

networks:
  mysql-net:

volumes:
  master_data:
  replica_data:
