FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

COPY master.cnf /etc/mysql/conf.d/master.cnf
COPY master-init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306
